import './globals.css'
import { poppins } from '../utils/fonts';
import Blob from '@/elements/Blob/Blob';
import Header from '@/components/Header/Header';
import Navigation from '@/components/Navigation/Navigation';


export const metadata = {
  title: 'Léo Legrand',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={poppins.className}>
        <Blob/>
        <Header/>
        {children}
        <Navigation/>
       </body>
    </html>
  )
}
